import streamlit as st  # 匯入streamlit模組並重新命名為st

# st.number_input ()可以讓使用者輸入數字，設定step=1可以讓適用者只能輸入整數
# min_value=0 可以設定最小值為0，max_value=100可以設定最大值為100
number = st.number_input("請輸入數字", step=1, min_value=0, max_value=100)
# st.markdown()可以在網頁使用Markdown語法顯示文字
st.markdown(f"您輸入的數字是: {number}")

st.markdown("---")
st.title("練習")
st.write("please enter your score")
score = st.number_input("請輸入分數", step=1, min_value=0, max_value=100)
if score >= 90:
    st.write("A")
elif 80 <= score < 90:
    st.write("B")
elif 70 <= score < 80:
    st.write("C")
elif 60 <= score < 70:
    st.write("D")
elif score < 60:
    st.write("F")
st.markdown("---")

st.markdown("### 按鈕練習")
# st.button()可以在網頁上顯示一個按鈕，使用者可以點擊
# key 是按鈕的識別名稱，可以用來區分不同的按鈕
# 如果使用者點擊按鈕，st.button()會回傳True，否則回傳False
st.button("按我一下", key="button1")

if st.button("按我一下", key="balloons"):
    st.balloons()
    st.balloons()
    st.balloons()
    st.balloons()
    st.balloons()
    st.balloons()
    st.balloons()
    st.balloons()
    st.balloons()
    st.balloons()
    st.balloons()
    st.balloons()
    st.balloons()
    st.balloons()
    st.balloons()
    st.balloons()
    st.balloons()
    st.balloons()
    st.balloons()
    st.balloons()
    st.balloons()
    st.balloons()
    st.balloons()
    st.balloons()
    st.balloons()
    st.balloons()
    st.balloons()
    st.balloons()
    st.balloons()
    st.balloons()
    st.balloons()
    st.balloons()
    st.balloons()
    st.balloons()
    st.balloons()
    st.balloons()
    st.balloons()
    st.balloons()
    st.balloons()
    st.balloons()
    st.balloons()
    st.balloons()
    st.balloons()
    st.balloons()
    st.balloons()
    st.balloons()
    st.balloons()
    st.balloons()
    st.balloons()
    st.balloons()
    st.balloons()
    st.balloons()
    st.balloons()
    st.balloons()
    st.balloons()
    st.balloons()
    st.balloons()
    st.balloons()
    st.balloons()
    st.balloons()
    st.balloons()
    st.balloons()
    st.balloons()
    st.balloons()
    st.balloons()
    st.balloons()
    st.balloons()
    st.balloons()
    st.balloons()
    st.balloons()
    st.balloons()
    st.balloons()
    st.balloons()
    st.balloons()
    st.balloons()
    st.balloons()
    st.balloons()
    st.balloons()
    st.balloons()
    st.balloons()
    st.balloons()
    st.balloons()
    st.balloons()
    st.balloons()
    st.balloons()
    st.balloons()
    st.balloons()
    st.balloons()
    st.balloons()
    st.balloons()
    st.balloons()
    st.balloons()
    st.balloons()
    st.balloons()
    st.balloons()
    st.balloons()
    st.balloons()
    st.balloons()
    st.balloons()
    st.balloons()
    st.balloons()
    st.balloons()
    st.balloons()
    st.balloons()
    st.balloons()
    st.balloons()
    st.balloons()
    st.balloons()
    st.balloons()
    st.balloons()
    st.balloons()
    st.balloons()
    st.balloons()
    st.balloons()
    st.balloons()
    st.balloons()
    st.balloons()
    st.balloons()
    st.balloons()
    st.balloons()
    st.balloons()
if st.button("按我一下", key="snow"):
    st.snow()
    st.snow()
    st.snow()
    st.snow()
    st.snow()
    st.snow()
    st.snow()
    st.snow()
    st.snow()
    st.snow()
    st.snow()
    st.snow()
    st.snow()
    st.snow()
    st.snow()
    st.snow()
    st.snow()
    st.snow()
    st.snow()
    st.snow()
    st.snow()
    st.snow()
    st.snow()
    st.snow()
    st.snow()
    st.snow()
    st.snow()
    st.snow()
    st.snow()
    st.snow()
    st.snow()
    st.snow()
    st.snow()
    st.snow()
    st.snow()
    st.snow()
    st.snow()
    st.snow()
    st.snow()
    st.snow()
    st.snow()
    st.snow()
    st.snow()
    st.snow()
    st.snow()
    st.snow()
    st.snow()
    st.snow()
    st.snow()
    st.snow()
    st.snow()
    st.snow()
    st.snow()
    st.snow()
    st.snow()
    st.snow()
    st.snow()
    st.snow()
    st.snow()
    st.snow()
    st.snow()
    st.snow()
    st.snow()
    st.snow()
    st.snow()
    st.snow()
    st.snow()
    st.snow()
    st.snow()
    st.snow()
    st.snow()
    st.snow()
    st.snow()
    st.snow()
    st.snow()
    st.snow()
    st.snow()
    st.snow()
    st.snow()
    st.snow()
    st.snow()
    st.snow()
st.markdown("---")
